trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallPython
  displayName: 'Install Python'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

- job: Build
  displayName: 'Build stage'
  dependsOn: InstallPython
  steps:
  - checkout: self
  - script: |
      sudo apt-get update
      sudo apt-get install python3-venv 
      python -m venv env
      source env/bin/activate
      pip install flask
      pip install pymongo
      pip install pytest
    displayName: 'Install dependencies'

- job: Test
  displayName: 'Test stage'
  dependsOn: Build
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - script: |
      python -m venv env
      source env/bin/activate
      pip install pytest
      pytest
      # Run pytest to collect test items
      pytest --collect-only
      # Check if any test items are collected
      if [ $(pytest --collect-only | grep -c "collected 0 items") -eq 0 ]; then
        # Run tests if there are collected test items
        pytest
      else
        # Pass if no test items are collected
        echo "No test items found. Skipping tests."
      fi
    displayName: 'Run tests'

