pipeline:
  agent: any
  environment: 
    FLASK_APP: "app.py"
    FLASK_ENV: "development"
  stages:
    - stage: Build
      steps: 
        - checkout
        - sh 'python -m venv env'
        - sh 'source env/bin/activate'
        - sh 'pip install -r requirements.txt'
    - stage: Test
      steps:
        - sh 'source env/bin/activate'
        - sh 'pytest'
    - stage: Deploy
      steps:
        - sh 'source env/bin/activate'
        - sh 'scp -r ./* Pasupathikumar@20.235.130.103:/home/Pasupathikumar/flask_project_1'
        - sh 'ssh Pasupathikumar@20.235.130.103 "source /home/Pasupathikumar/flask_project_1/env/bin/activate && nohup python /home/Pasupathikumar/flask_project_1/app.py &"'